# Generated by Django 4.2.8 on 2023-12-31 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='insert',
            old_name='sname',
            new_name='email',
        ),
        migrations.AddField(
            model_name='insert',
            name='message',
            field=models.TextField(default='Me nhi bataunga'),
        ),
        migrations.AddField(
            model_name='insert',
            name='subject',
            field=models.CharField(default='Me nhi bataunga', max_length=100),
        ),
    ]
