# Generated by Django 4.2.8 on 2023-12-31 14:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_sname_insert_email_insert_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='insert',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 12, 31, 19, 48, 30, 720306)),
        ),
        migrations.AlterField(
            model_name='insert',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='insert',
            name='subject',
            field=models.CharField(max_length=100),
        ),
    ]
