# Generated by Django 4.2.8 on 2023-12-31 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_insert_date_alter_insert_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insert',
            name='date',
            field=models.DateField(),
        ),
    ]
